version: '3.8'

services:
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example_password
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_LOGLEVEL: DEBUG
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n"
    depends_on:
      - postgresql
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data

  redis:
    image: redis
    restart: always
    environment:
      REDIS_PASSWORD: password
    volumes:
      - redis_data:/data

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data

  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data

volumes:
  postgresql_data:
  keycloak_data:
  redis_data:
  kafka_data:
  zookeeper_data:
