auth:
  keycloak:
    config:
      client-id: auth-service
      default-role: user
      realm: social
      domain: http://localhost:9090
      admin-client-id: admin-auth-service
      admin-client-secret: rS2nm3dOVd4phbcL1Jb1YFMiCSIx6JrZ
server:
  port: 8081

spring:
  #       form data enable
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
#      application name
  application:
    name: user-service
#      data source properties
  datasource:
    username: root
    url: jdbc:h2:file:./social;DB_CLOSE_ON_EXIT=FALSE
    password: sa
#    update config at last
  config:
    import: configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8083}
  jpa:
    hibernate:
      ddl-auto: create